import { buildShareMeta, escapeHtml } from './banner-generator';

export interface ProductCodeSettings {
  imageUrl: string;
  linkUrl: string;
  alt: string;
  oldPricePercent: number;
  oldPriceFixed: number;
  shareDescription: string;
}

function positive(value: number): number {
  return Number.isFinite(value) && value > 0 ? value : 0;
}

export function buildProductsCode(settings: ProductCodeSettings): string {
  const percent = positive(settings.oldPricePercent);
  const fixed = percent ? 0 : positive(settings.oldPriceFixed);
  const meta = buildShareMeta(settings.shareDescription, 'hs-share-description');
  const content = `<!-- MT INLINE PRODUCTS START -->
<div class="hs-page-banner" data-alt="${escapeHtml(settings.alt)}" data-image-url="${escapeHtml(settings.imageUrl)}" data-link-url="${escapeHtml(settings.linkUrl)}" hidden id="hs-page-banner"></div>
<section class="hs-products" data-old-price-percent="${percent || ''}" data-old-price-fixed="${fixed || ''}" hidden id="hs-inline-products"><div class="hs-products__mount"></div></section>
<style type="text/css">
.hs-page-banner[hidden],.hs-products[hidden]{display:none!important}.hs-page-banner{width:100%;max-width:1200px;margin:0 auto 32px}.hs-page-banner__link{display:block;overflow:hidden;border-radius:16px}.hs-page-banner__image{display:block;width:100%!important;height:auto!important;aspect-ratio:3/1;object-fit:cover}.hs-products{margin:40px 0;font-family:inherit}.hs-products__native{margin:0!important;padding:0!important;overflow:visible!important}.hs-products__native .product-heading,.hs-products__native .swiper-button-prev,.hs-products__native .swiper-button-next,.hs-products__native .swiper-pagination,.hs-products__native .carousel__nav{display:none!important}.hs-products__native .productsSlider-wrapper,.hs-products__native .carousel__wrapper,.hs-products__native .swiper-wrapper{position:static!important;display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px;transform:none!important;width:auto!important;height:auto!important}.hs-products__native .productsSlider-i,.hs-products__native .carousel__item,.hs-products__native .swiper-slide,.hs-products__native .catalog-card{display:flex!important;flex-direction:column;width:auto!important;height:auto!important;margin:0!important;padding:18px!important;box-sizing:border-box;border:1px solid #e7e9ee;border-radius:16px;background:#fff;box-shadow:0 6px 24px rgba(20,30,55,.07)}.hs-products__native img{max-width:100%!important;object-fit:contain!important}.hs-products__native .productsSlider-price,.hs-products__native .catalog-card__price{color:#f00!important;font-weight:800!important}.hs-products-old-price{display:block!important;margin:0 0 5px!important;color:#8a8f98!important;font-size:16px!important;font-weight:500!important;text-decoration:line-through!important}.hs-products__native .btn{width:100%!important;box-sizing:border-box}@media(max-width:980px){.hs-products__native .productsSlider-wrapper,.hs-products__native .carousel__wrapper,.hs-products__native .swiper-wrapper{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:720px){.hs-products__native .productsSlider-wrapper,.hs-products__native .carousel__wrapper,.hs-products__native .swiper-wrapper{grid-template-columns:1fr;gap:14px}}
</style>
<script>(function(){"use strict";var root=document.getElementById("hs-inline-products"),banner=document.getElementById("hs-page-banner");if(!root)return;function mountBanner(){if(!banner)return;var src=(banner.getAttribute("data-image-url")||"").trim();if(!src){banner.remove();return}var link=document.createElement("a"),img=document.createElement("img"),href=(banner.getAttribute("data-link-url")||"").trim();link.className="hs-page-banner__link";if(href)link.href=href;img.className="hs-page-banner__image";img.src=src;img.alt=banner.getAttribute("data-alt")||"";img.width=1200;img.height=400;link.appendChild(img);banner.appendChild(link);banner.hidden=false}function source(){var list=document.querySelectorAll(".article__associated-products,.page__associated-products,.textPage__associated-products,[class*='associated-products'],.related-goods");for(var i=0;i<list.length;i++){if(!root.contains(list[i])&&(list[i].querySelector(".productsSlider-i")||list[i].querySelector(".catalog-card")))return list[i]}return null}function oldPrices(node){var p=Number(root.getAttribute("data-old-price-percent")||0),f=Number(root.getAttribute("data-old-price-fixed")||0);if(!(p>0)&&!(f>0))return;var prices=node.querySelectorAll(".productsSlider-price,.catalog-card__price");Array.prototype.forEach.call(prices,function(price){if(price.querySelector(".hs-products-old-price"))return;var text=(price.textContent||"").trim(),match=text.match(/\\d[\\d\\s\\u00a0]*(?:[.,]\\d{1,2})?/);if(!match)return;var current=Number(match[0].replace(/[\\s\\u00a0]/g,"").replace(",","."));if(!Number.isFinite(current))return;var old=p>0?Math.floor((current*(1+p/100))/10)*10:Math.round((current+f)*100)/100,span=document.createElement("span");span.className="hs-products-old-price";span.textContent=new Intl.NumberFormat("uk-UA",{maximumFractionDigits:2}).format(old)+" грн";price.insertBefore(span,price.firstChild)});Array.prototype.forEach.call(node.querySelectorAll("a[href]"),function(link){try{var url=new URL(link.href,location.href);if(url.origin!==location.origin)return;if(p>0)url.searchParams.set("mt_old_percent",String(p));else url.searchParams.set("mt_old_fixed",String(f));url.searchParams.set("mt_promo_price","1");link.href=url.toString()}catch(e){}})}function mount(){if(root.dataset.initialized==="true")return true;var node=source();if(!node)return false;node.classList.add("hs-products__native");root.querySelector(".hs-products__mount").appendChild(node);oldPrices(node);root.hidden=false;root.dataset.initialized="true";return true}mountBanner();if(!mount()){var observer=new MutationObserver(function(){if(mount())observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(function(){observer.disconnect()},8000)}})();</script>
<!-- MT INLINE PRODUCTS END -->`;
  return meta ? `${meta}\n${content}` : content;
}

export function buildGlobalProductCode(): string {
  return `<!-- MT GLOBAL PRODUCT PRICE START -->
<style type="text/css">.mt-product-price-stack{display:flex!important;flex-direction:column!important;align-items:flex-start!important}.mt-product-current-price{color:#f00!important}.mt-product-old-price{display:block!important;margin:0 0 4px!important;color:#8a8f98!important;font-size:16px!important;font-weight:500!important;text-decoration:line-through!important}</style>
<script>(function(){"use strict";var params=new URLSearchParams(location.search),enabled=params.get("mt_promo_price")==="1",percent=Number(params.get("mt_old_percent")||0),fixed=Number(params.get("mt_old_fixed")||0);if(!enabled||(!(percent>0)&&!(fixed>0)))return;function parse(text){var match=String(text||"").match(/\\d[\\d\\s\\u00a0]*(?:[.,]\\d{1,2})?/);return match?Number(match[0].replace(/[\\s\\u00a0]/g,"").replace(",",".")):null}function apply(){var selectors=[".product-card__price",".product-price__item",".product-price__current",".product-price__value",".product-price",".product__price",".product-info__price","[itemprop='price']:not(meta)"];for(var i=0;i<selectors.length;i++){var nodes=document.querySelectorAll(selectors[i]);for(var j=0;j<nodes.length;j++){var price=nodes[j],value=parse(price.textContent);if(value===null||price.querySelector(".mt-product-old-price"))continue;var old=percent>0?Math.floor((value*(1+percent/100))/10)*10:Math.round((value+fixed)*100)/100,span=document.createElement("span");span.className="mt-product-old-price";span.textContent=new Intl.NumberFormat("uk-UA",{maximumFractionDigits:2}).format(old)+" грн";price.classList.add("mt-product-current-price");price.parentNode.classList.add("mt-product-price-stack");price.parentNode.insertBefore(span,price);return true}}return false}apply();var observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true})})();</script>
<!-- MT GLOBAL PRODUCT PRICE END -->`;
}
