import type { PopupPromoProduct } from '../../types/popup-banner';
import { CollectionSettings } from './CollectionSettings';
import { useState, type ReactNode } from 'react';
import { StyledSelect } from '../StyledSelect';
import { blockLabels, effectiveStyle, isContainer, type BlockNode, type BlockProps, type BlockStyle, type Device } from './block-model';

export function Property({ label, children }: { label: string; children: ReactNode }) { return <div className="pb-property"><span>{label}</span>{children}</div>; }
function Group({ title, children }: { title: string; children: ReactNode }) { return <details className="pb-group" open><summary>{title}</summary><div>{children}</div></details>; }
export function Choice<T extends string | number>({ label, value, options, onChange }: { label: string; value: T; options: readonly (readonly [T, string])[]; onChange: (value: T) => void }) {
  return <Property label={label}><StyledSelect ariaLabel={label} value={value} onChange={onChange} options={options.map(([value, label]) => ({ value, label }))} /></Property>;
}
export function BlockInspector({ node, device, onChange, productPicker, productBinding, products, live = false }: { products?: PopupPromoProduct[]; node: BlockNode; device: Device; onChange: (node: BlockNode) => void; productPicker?: ReactNode; productBinding?: ReactNode; live?: boolean }) {
  const [linked, setLinked] = useState(true);
  const style = effectiveStyle(node, device);
  const setStyle = (patch: Partial<BlockStyle>) => onChange(device === 'mobile' ? { ...node, mobile: { ...node.mobile, ...patch } } : { ...node, style: { ...node.style, ...patch } });
  const setProp = <K extends keyof BlockProps>(key: K, value: BlockProps[K]) => onChange({ ...node, props: { ...node.props, [key]: value } });
  const text = (key: keyof BlockProps, label: string, maxLength = 3000, multiline = false) => <Property label={label}>{multiline ? <textarea aria-label={label} value={String(node.props[key])} maxLength={maxLength} onChange={(event) => setProp(key, event.target.value)} rows={3} /> : <input aria-label={label} value={String(node.props[key])} maxLength={maxLength} onChange={(event) => setProp(key, event.target.value)} />}</Property>;
  const number = (key: keyof BlockStyle, label: string, min = 0, max = 120, step = 1) => <Property label={label}><input aria-label={label} type="number" value={Number(style[key])} min={min} max={max} step={step} onChange={(event) => { if (event.target.value !== '') setStyle({ [key]: Math.max(min, Math.min(max, Number(event.target.value))) }); }} /></Property>;
  const choice = <K extends keyof BlockStyle>(key: K, label: string, options: readonly (readonly [BlockStyle[K] & (string | number), string])[]) => <Choice label={label} value={style[key] as BlockStyle[K] & (string | number)} options={options} onChange={(value) => setStyle({ [key]: value })} />;
  const check = (key: keyof BlockStyle, label: string) => <label className="pb-check"><input type="checkbox" checked={Boolean(style[key])} onChange={(event) => setStyle({ [key]: event.target.checked })} />{label}</label>;
  const color = (key: 'color' | 'background' | 'borderColor', label: string) => <Property label={label}><div className="pb-color"><input type="color" aria-label={label} value={style[key] === 'transparent' ? '#ffffff' : style[key]} onChange={(event) => setStyle({ [key]: event.target.value })} /><code>{style[key]}</code>{key !== 'color' && <button type="button" title="Прозорий" aria-label={label + ': прозорий'} onClick={() => setStyle({ [key]: 'transparent' })}>∅</button>}</div></Property>;
  const sides = (prefix: 'padding' | 'margin', label: string) => <fieldset className="pb-spacing"><legend>{label}</legend><div>{(['Top', 'Right', 'Bottom', 'Left'] as const).map((side, index) => { const key = (prefix + side) as keyof BlockStyle; const sideLabel = label + ': ' + ['зверху', 'справа', 'знизу', 'зліва'][index]; return <label key={side}><span>{['↑', '→', '↓', '←'][index]}</span><input type="number" aria-label={sideLabel} value={Number(style[key])} min={prefix === 'padding' ? 0 : -80} max={120} onChange={(event) => { if (!event.target.value) return; const value = Math.max(prefix === 'padding' ? 0 : -80, Math.min(120, Number(event.target.value))); setStyle(linked ? Object.fromEntries(['Top', 'Right', 'Bottom', 'Left'].map((suffix) => [prefix + suffix, value])) : { [key]: value }); }} /></label>; })}</div></fieldset>;
  return <div className="pb-inspector-content">
    <div className="pb-inspector-title"><small>{blockLabels[node.type]}</small><h2>{node.name || 'Без назви'}</h2></div>
    <Property label="Назва в дереві"><input aria-label="Назва в дереві" value={node.name} maxLength={120} onChange={(event) => onChange({ ...node, name: event.target.value })} /></Property>
    <div className="pb-device-note">{device === 'mobile' ? <>Стилі Mobile · {Object.keys(node.mobile).length} перевизначень<button type="button" disabled={!Object.keys(node.mobile).length} onClick={() => onChange({ ...node, mobile: {} })}>Успадкувати всі стилі Desktop</button></> : 'Стилі Desktop · основа для Mobile'}</div>
    {productPicker && <Group title={node.type === 'product' ? 'Товар блока' : 'Товар банера'}>{productPicker}</Group>}
    {node.type === 'collection' && <Group title="Добірка товарів"><CollectionSettings products={products} node={node} onChange={onChange} /></Group>}
    <Group title="Вміст">
      {live && ((['text', 'image'].includes(node.type) && node.props.binding !== 'none') || (node.type === 'button' && ['product', 'cart'].includes(node.props.action))) && <Choice label="Дані якого товару" value={node.props.dataSource} options={ [['inherit', 'Успадкувати від контейнера'], ['page', 'Товар відкритої сторінки'], ['banner', 'Закріплений товар банера'], ['item', 'Товар поточної картки добірки']] } onChange={value => setProp('dataSource', value)} />}
      {['text', 'image'].includes(node.type) && <Choice label="Джерело вмісту" value={node.props.binding} options={node.type === 'image' ? [['none', 'Власне зображення'], ['product.image', 'Фото товару']] : [['none', 'Власний текст'], ['product.title', 'Назва товару'], ['product.variant', live ? 'Артикул товару' : 'Характеристики'], ['product.price', 'Ціна'], ['product.oldPrice', 'Стара ціна'], ['product.badge', 'Позначка товару']]} onChange={(value) => setProp('binding', value)} />}
      {['text', 'button', 'field', 'acknowledgement'].includes(node.type) && (node.props.binding === 'none' || node.type !== 'text') && text('text', node.type === 'field' ? 'Підпис поля' : 'Текст елемента', 3000, node.type === 'text')}
      {((['text', 'image'].includes(node.type) && node.props.binding !== 'none') || (node.type === 'button' && ['product', 'cart'].includes(node.props.action))) && (live ? productBinding : <p className="pb-help">Вміст успадковується від найближчого блока «Товар». Для перевірки використовується демокаталог.</p>)}
      {node.type === 'image' && <>{node.props.binding === 'none' && text('src', 'URL зображення', 2000)}{text('alt', 'Альтернативний текст', 240)}<Choice label="Заповнення зображення" value={node.props.imageFit} options={ [['contain', 'Вписати'], ['cover', 'Заповнити з обрізанням']] } onChange={(value) => setProp('imageFit', value)} /><Choice label="Позиція зображення" value={node.props.imagePosition} options={ [['center', 'Центр'], ['top', 'Зверху'], ['bottom', 'Знизу'], ['left', 'Зліва'], ['right', 'Справа']] } onChange={(value) => setProp('imagePosition', value)} /></>}
      {node.type === 'button' && <><Choice label="Дія кнопки" value={node.props.action} options={ [['link', 'Перейти за посиланням'], ['close', 'Закрити банер'], ['copy', 'Скопіювати промокод'], ['submit', 'Надіслати форму'], ['product', 'Відкрити товар'], ['cart', 'Додати товар у кошик']] } onChange={(value) => setProp('action', value)} />{node.props.action === 'link' && <>{text('href', 'Посилання', 2000)}<label className="pb-check"><input type="checkbox" checked={node.props.newTab} onChange={(event) => setProp('newTab', event.target.checked)} />У новій вкладці</label></>}{node.props.action === 'copy' && node.props.couponSource === 'custom' && text('code', 'Промокод', 80)}</>}
      {node.type === 'coupon' && <>{node.props.couponSource === 'custom' && text('code', 'Промокод', 80)}{text('copyLabel', 'Підпис копіювання', 120)}</>}
      {live && (node.type === 'coupon' || (node.type === 'button' && node.props.action === 'copy')) && <Choice label="Джерело промокоду" value={node.props.couponSource} options={ [['custom', 'Власний код'], ['campaign', 'Бібліотека промокодів кампанії']] } onChange={value => setProp('couponSource', value)} />}
      {node.type === 'form' && <>{live && <Choice label="Після заповнення" value={node.props.reward} options={ [['none', 'Подяка'], ['promo_code', 'Видати промокод кампанії']] } onChange={value => setProp('reward', value)} />}{text('successMessage', 'Повідомлення після відправлення', 1000, true)}<p className="pb-help">У тестовому перегляді форма перевіряє поля й показує результат. Контакти нікуди не надсилаються.</p></>}
      {node.type === 'field' && <><Choice label="Тип поля" value={node.props.fieldType} options={ [['text', 'Текст'], ['email', 'Email'], ['phone', 'Телефон'], ['textarea', 'Багаторядковий текст'], ['select', 'Список'], ['checkbox', 'Прапорець']] } onChange={(value) => setProp('fieldType', value)} />{text('placeholder', 'Підказка поля', 200)}{node.props.fieldType === 'select' && text('options', 'Варіанти — кожен з нового рядка', 1600, true)}<label className="pb-check"><input type="checkbox" checked={node.props.required} onChange={(event) => setProp('required', event.target.checked)} />Обов’язкове поле</label></>}
      {node.type === 'product' && !live && <Choice label="Демотовар" value={node.props.productId} options={ [['titanium', 'iPhone 16 Pro'], ['blue', 'iPhone 15'], ['pink', 'iPhone 16'], ['black', 'iPhone 16 Pro Max']] } onChange={(value) => setProp('productId', value)} />}
      {node.type === 'countdown' && <><Choice label="Режим таймера" value={node.props.timerMode} options={ [['duration', 'Відлік від відкриття'], ['deadline', 'До дати й часу']] } onChange={(value) => setProp('timerMode', value)} />{node.props.timerMode === 'duration' ? <Property label="Тривалість, хв"><input type="number" aria-label="Тривалість, хв" min={1} max={43200} value={node.props.durationMinutes} onChange={(event) => setProp('durationMinutes', Math.max(1, Math.min(43200, Number(event.target.value))))} /></Property> : <Property label="Дата завершення"><input type="datetime-local" aria-label="Дата завершення" value={localDeadline(node.props.deadlineAt)} onChange={(event) => setProp('deadlineAt', event.target.value ? new Date(event.target.value).toISOString() : '')} /><small>Часовий пояс цього пристрою</small></Property>}<label className="pb-check"><input type="checkbox" checked={node.props.hideOnExpire} onChange={(event) => setProp('hideOnExpire', event.target.checked)} />Приховати банер після завершення</label></>}
      {['container', 'divider', 'spacer'].includes(node.type) && <p className="pb-help">{isContainer(node) ? 'Вкладайте елементи та контейнери на будь-якому рівні дерева.' : 'Розміри й оформлення налаштовуються нижче.'}</p>}
    </Group>
    {isContainer(node) && node.type !== 'collection' && <Group title="Розташування дочірніх блоків">{choice('direction', 'Напрямок', [['row', 'Горизонтально →'], ['column', 'Вертикально ↓']])}{check('wrap', 'Переносити на новий рядок')}{choice('justify', 'Розподіл уздовж осі', [['flex-start', 'На початку'], ['center', 'По центру'], ['flex-end', 'У кінці'], ['space-between', 'Між елементами'], ['space-around', 'Навколо елементів']])}{choice('align', 'Вирівнювання поперек осі', [['stretch', 'Розтягнути'], ['flex-start', 'На початку'], ['center', 'По центру'], ['flex-end', 'У кінці']])}<div className="pb-two">{number('gap', 'Проміжок колонок')}{number('rowGap', 'Проміжок рядків')}</div></Group>}
    <Group title="Розміри">{choice('widthMode', 'Ширина', [['auto', 'За вмістом'], ['fill', 'Заповнити'], ['fixed', 'Фіксована · px'], ['percent', 'Відсотки · %']])}{['fixed', 'percent'].includes(style.widthMode) && number('width', 'Значення ширини', 1, style.widthMode === 'percent' ? 100 : 1400)}{choice('heightMode', 'Висота', [['auto', 'За вмістом'], ['fixed', 'Фіксована · px']])}{style.heightMode === 'fixed' && number('height', 'Значення висоти', 1, 1600)}<div className="pb-two">{number('minHeight', 'Мін. висота', 0, 1200)}{number('maxWidth', 'Макс. ширина', 0, 1400)}</div><small className="pb-help">Максимальна ширина 0 — без обмеження.</small>{number('grow', 'Займати вільний простір', 0, 10)}{check('shrink', 'Дозволити стискання')}</Group>
    <Group title="Відступи"><label className="pb-check"><input type="checkbox" checked={linked} onChange={(event) => setLinked(event.target.checked)} />Зв’язати чотири сторони</label>{sides('padding', 'Внутрішній відступ')}{sides('margin', 'Зовнішній відступ')}</Group>
    <Group title="Оформлення">{color('background', 'Фон')}{color('color', 'Колір тексту')}{number('radius', 'Заокруглення', 0, 100)}{choice('shadow', 'Тінь', [['none', 'Без тіні'], ['soft', 'Легка'], ['medium', 'Середня'], ['large', 'Велика']])}{number('borderWidth', 'Товщина рамки', 0, 12)}{style.borderWidth > 0 && <>{color('borderColor', 'Колір рамки')}{choice('borderStyle', 'Стиль рамки', [['solid', 'Суцільна'], ['dashed', 'Штрихова'], ['dotted', 'Крапкова']])}</>}{number('opacity', 'Непрозорість', 0, 1, 0.05)}{choice('overflow', 'Вміст за межами блока', [['visible', 'Показувати'], ['hidden', 'Обрізати']])}{check('hidden', 'Приховати на цьому пристрої')}</Group>
    {!['image', 'divider', 'spacer'].includes(node.type) && <Group title="Типографіка">{choice('fontFamily', 'Шрифт', [['inherit', 'Системний'], ['Arial, sans-serif', 'Arial'], ['Georgia, serif', 'Georgia'], ['monospace', 'Моноширинний']])}<div className="pb-two">{number('fontSize', 'Розмір шрифту', 8, 96)}{number('fontWeight', 'Насиченість', 300, 800, 50)}{number('lineHeight', 'Міжрядковий інтервал', 1, 3, 0.1)}{number('letterSpacing', 'Відстань між літерами', -5, 15, 0.1)}</div>{choice('textAlign', 'Вирівнювання тексту', [['left', 'Зліва'], ['center', 'По центру'], ['right', 'Справа']])}{check('italic', 'Курсив')}{check('underline', 'Підкреслення')}</Group>}
  </div>;
}

function localDeadline(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
