import { useEffect, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { useConfirmDialog } from '../../dialogs/ConfirmDialogContext';
import { Choice, Property } from './BlockInspector';
import { CampaignRules } from './CampaignRules';
import { CatalogBlockPicker } from './CatalogBlockPicker';
import { CollectionSettings } from './CollectionSettings';
import { createTemplate, type TemplateName } from './templates';
import { flatten, patchBlock, type BlockDocument } from './block-model';
import { fieldLabels } from './RuleEditor';
import type { PopupCampaignInput, PopupInspection, PopupPreviewPayload } from '../../types/popup-banner';

const scenarios: { id: TemplateName; title: string; description: string }[] = [
  { id: 'alternatives', title: 'Альтернативи відсутнього товару', description: 'Доступні моделі з категорії відкритого товару. Автоматична добірка та власний дизайн картки.' },
  { id: 'product', title: 'Товарна пропозиція', description: 'Закріплений товар, ціни, фото, перехід або додавання до кошика.' },
  { id: 'warning', title: 'Інформація та підтвердження', description: 'Попередження для потрібних товарів. Кнопка «Ознайомлений».' },
  { id: 'coupon', title: 'Промокод', description: 'Відкрита пропозиція з копіюванням промокоду кампанії.' },
  { id: 'form', title: 'Контактна форма за промокод', description: 'Довільні поля. Промокод видається лише після успішного збереження контакту.' },
  { id: 'countdown', title: 'Пропозиція з таймером', description: 'До дати або персональний відлік. Приховування після завершення.' },
  { id: 'blank', title: 'Власний сценарій', description: 'Порожній макет, довільні блоки, дані та правила.' }
];
export function applyScenario(input: PopupCampaignInput, name: TemplateName): PopupCampaignInput {
  return { ...input, targeting: { ...input.targeting, mode: name === 'alternatives' ? 'out_of_stock' : 'all_pages', rules: undefined, exclusions: undefined }, behavior: { ...input.behavior, requireAcknowledgement: name === 'warning', dismissible: true } };
}
interface Props { campaignId?: string; tab: string; input: PopupCampaignInput; onChange: (input: PopupCampaignInput) => void; document: BlockDocument; onDocument: (document: BlockDocument) => void; onSelect: (id: string) => void; contextUrl: string; onContextUrl: (url: string) => void; preview: PopupPreviewPayload | null; promoCode?: string; onChooseCode: () => void }
export function CampaignWorkspace(props: Props) {
  const { tab, input, onChange, document, onDocument, onSelect, contextUrl, onContextUrl, preview } = props;
  const confirm = useConfirmDialog();
  const options = useQuery({ queryKey: ['popup-campaign-options'], queryFn: api.popupBanners.options });
  if (tab === 'rules') return <CampaignRules input={input} onChange={onChange} options={options.data} />;
  if (tab === 'test') return <CampaignTester campaignId={props.campaignId} input={{ ...input, blockDocument: document }} url={contextUrl} onUrl={onContextUrl} />;
  const collections = flatten(document.root).filter(({ node }) => node.type === 'collection');
  return <div className="pc-workspace"><section><small>СЦЕНАРІЙ КАМПАНІЇ</small><h2>Що має зробити цей банер</h2><p>Сценарій задає початковий макет і правила. Після цього кожен блок і кожну умову можна змінити.</p><div className="pc-scenarios">{scenarios.map(scenario => <button type="button" key={scenario.id} onClick={() => { void confirm({ title: 'Застосувати сценарій «' + scenario.title + '»?', message: 'Буде замінено макет, початкову аудиторію, додаткові правила та виключення. Частота, розклад і вибраний промокод збережуться. Заміна макета доступна в історії дизайну.', confirmLabel: 'Застосувати сценарій' }).then(ok => { if (!ok) return; onChange(applyScenario(input, scenario.id)); onDocument(createTemplate(scenario.id, true)); }); }}><strong>{scenario.title}</strong><span>{scenario.description}</span></button>)}</div></section>
    <section><h2>Контекст сторінки для прев’ю</h2><Property label="URL товару для прикладу"><input aria-label="URL товару для прикладу" placeholder={'https://' + (options.data?.integration?.storeDomain || 'магазин') + '/товар/'} value={contextUrl} onChange={e => onContextUrl(e.target.value)} /></Property><p>Використовується лише для перегляду. На сайті контекст визначається з відкритої сторінки та вибраної модифікації.</p>{preview?.pageProduct && <p className="pc-callout">Товар сторінки: {preview.pageProduct.title} · {preview.pageProduct.sku}</p>}</section>
    <section><h2>Закріплений товар банера</h2><p>Окреме джерело для статичної пропозиції. Альтернативам воно не потрібне.</p><CatalogBlockPicker node={document.root} product={preview?.products.find(p => p.productExternalId === document.root.props.productExternalId && (p.modificationExternalId || '') === document.root.props.modificationExternalId)} onChange={root => onDocument({ ...document, root })} /></section>
    {collections.map(({ node }) => <section key={node.id}><div className="pc-inline"><h2>{node.name}</h2><button type="button" onClick={() => onSelect(node.children[0].id)}>Редагувати шаблон картки</button></div><CollectionSettings products={preview?.products} node={node} onChange={next => onDocument({ ...document, root: patchBlock(document.root, next.id, () => next) })} /><p>У прикладі знайдено: {preview?.collections?.[node.id]?.length || 0} товарів.</p></section>)}
    <section><h2>Промокод кампанії</h2><strong>{props.promoCode || 'Не вибрано'}</strong><div className="pc-inline"><button type="button" onClick={props.onChooseCode}>Обрати промокод</button>{input.promoCodeId && <button type="button" onClick={() => onChange({ ...input, promoCodeId: null })}>Відв’язати промокод</button>}</div><p>У блоці промокоду або формі виберіть джерело «Промокод кампанії». Поля та результат форми, режими таймера налаштовуються безпосередньо у властивостях відповідного блока.</p></section>
  </div>;
}
function CampaignTester({ input, url, onUrl, campaignId }: { campaignId?: string; input: PopupCampaignInput; url: string; onUrl: (url: string) => void }) {
  const [device, setDevice] = useState<'desktop' | 'mobile'>('desktop');
  const [stockState, setStockState] = useState<'catalog' | 'unknown' | 'available' | 'out_of_stock'>('catalog');
  const [article, setArticle] = useState(''); const [seen, setSeen] = useState(false);
  const [now, setNow] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [result, setResult] = useState<{ value: PopupInspection; key: string } | null>(null);
  const resultRef = useRef<HTMLElement>(null);
  useEffect(() => { if (result) resultRef.current?.scrollIntoView({ block: 'start', behavior: 'smooth' }); }, [result]);
  const request = { campaignId, campaign: input, pageUrl: url, article, device, stockState, seen, ...(now ? { now: new Date(now).toISOString() } : {}) };
  const requestKey = JSON.stringify(request); const stale = result?.key !== requestKey;
  return <div className="pc-workspace"><section><small>ПЕРЕВІРКА ЧЕРНЕТКИ</small><h2>Чому банер з’явиться або не з’явиться</h2><p>Перевірка читає каталог. Вона не відкриває сторінку відвідувача й не створює контакти або замовлення. Частота та наявність можуть бути задані як симуляція.</p><Property label="URL для перевірки"><input aria-label="URL для перевірки" value={url} onChange={e => onUrl(e.target.value)} /></Property><Property label="Артикул модифікації (необов’язково)"><input aria-label="Артикул модифікації" value={article} onChange={e => setArticle(e.target.value)} /></Property><div className="pc-inline"><Choice label="Пристрій перевірки" value={device} options={ [['desktop', 'Desktop'], ['mobile', 'Mobile']] } onChange={setDevice} /><Choice label="Наявність у перевірці" value={stockState} options={ [['catalog', 'Дані каталогу'], ['out_of_stock', 'Симуляція: немає в наявності'], ['available', 'Симуляція: у наявності'], ['unknown', 'Симуляція: невідомо']] } onChange={setStockState} /></div><Property label="Симуляція дати (час цього пристрою)"><input aria-label="Симуляція дати" type="datetime-local" value={now} onChange={e => setNow(e.target.value)} /></Property><label><input type="checkbox" checked={seen} onChange={e => setSeen(e.target.checked)} /> Симулювати досягнутий ліміт частоти</label><p>Момент показу: {{ delay: 'після затримки', scroll: 'прокручування', inactivity: 'бездіяльність', exit_intent: 'намір вийти' }[input.behavior.trigger]}, не раніше {input.behavior.delayMs / 1000} с. Нижче перевіряється придатність кампанії після настання цієї події.</p><button className="pp-primary" type="button" disabled={busy || !url.trim()} onClick={() => { setBusy(true); setError(''); void api.popupBanners.inspect(request).then(value => setResult({ value, key: requestKey })).catch(caught => setError(caught instanceof Error ? caught.message : 'Помилка перевірки')).finally(() => setBusy(false)); }}>{busy ? 'Перевіряємо…' : 'Перевірити сторінку'}</button>{error && <p role="alert">{error}</p>}</section>
    {result && <section ref={resultRef} aria-label="Результат перевірки">{stale && <p className="pc-callout">Налаштування змінилися. Запустіть перевірку повторно.</p>}<h2>{result.value.eligible ? 'Кампанія відповідає умовам показу' : 'Кампанія не буде показана'}</h2><p>{result.value.product ? result.value.product.title + ' · ' + result.value.product.sku : 'Товар не визначено'}</p><p>{result.value.categoryPath}</p><p>{result.value.stockSource}: {result.value.stockState}</p><ul className="pc-checks">{result.value.checks.map(c => <li key={c.label} data-pass={c.pass}>{c.pass ? '✓' : '×'} {c.label}</li>)}</ul>{result.value.unmatched.length > 0 && <p role="alert">Не знайдено: {result.value.unmatched.join(', ')}</p>}{(['include', 'exclude'] as const).map(kind => <div key={kind}><h3>{kind === 'include' ? 'Додаткові умови' : 'Виключення'}</h3>{result.value.audience[kind].traces.map(trace => <p key={trace.path}>{trace.result === null ? '?' : trace.result ? '✓' : '×'} {fieldLabels[trace.field]}: очікується {trace.expected.join(', ')}; визначено {Array.isArray(trace.actual) ? trace.actual.join(', ') : trace.actual ?? 'невідомо'}</p>)}</div>)}<h3>Інші кампанії на цій сторінці</h3><p>Ваш пріоритет: {input.priority}. Відвідувач побачить одну кампанію з найвищим пріоритетом серед тих, чия подія вже настала і частота дозволяє показ.</p>{result.value.competitors.length ? result.value.competitors.map((c, i) => <p key={i}>{c.name} · пріоритет {c.priority} · не раніше {c.delayMs / 1000} с. {c.priority > input.priority ? 'Може випередити цю кампанію.' : c.priority === input.priority ? 'Однаковий пріоритет — порядок публікацій.' : 'Нижчий пріоритет.'}</p>) : <p>Інших придатних активних кампаній не знайдено.</p>}{result.value.collections.map(collection => <div key={collection.id}><h3>{collection.name}: {collection.count} / мінімум {collection.minimum}</h3><div className="pc-result-products">{result.value.preview.collections?.[collection.id]?.map(product => <article key={product.id}><img src={product.imageUrl} alt="" /><strong>{product.title}</strong><span>{product.sku} · {product.price} {product.currency}</span></article>)}</div><details><summary>Відхилені кандидати ({collection.rejected.length})</summary>{collection.rejected.map((item, i) => <p key={i}>{item.title} — {item.reason}</p>)}</details></div>)}</section>}
  </div>;
}
