import { useState } from 'react';
import type { PopupBehavior, PopupCampaignInput, PopupCampaignOptions } from '../../types/popup-banner';
import { Choice, Property } from './BlockInspector';
import { RuleEditor, describeRules, emptyGroup } from './RuleEditor';

function zonedDate(value: string | null, zone: string) {
  if (!value) return '';
  const parts = Object.fromEntries(new Intl.DateTimeFormat('sv-SE', { timeZone: zone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(value)).map(p => [p.type, p.value]));
  return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;
}
function toInstant(value: string, zone: string) {
  let instant = Date.parse(value + 'Z');
  for (let i = 0; i < 3; i++) instant += Date.parse(value + 'Z') - Date.parse(zonedDate(new Date(instant).toISOString(), zone) + 'Z');
  return new Date(instant).toISOString();
}
export function CampaignRules({ input, onChange, options }: { input: PopupCampaignInput; onChange: (input: PopupCampaignInput) => void; options?: PopupCampaignOptions }) {
  const [section, setSection] = useState('audience');
  const [dateError, setDateError] = useState('');
  const b = input.behavior, t = input.targeting;
  const behavior = (patch: Partial<PopupBehavior>) => onChange({ ...input, behavior: { ...b, ...patch } });
  const targeting = (patch: Partial<typeof t>) => onChange({ ...input, targeting: { ...t, ...patch } });
  const number = (key: keyof PopupBehavior, label: string, min: number, max: number, factor = 1) => <Property label={label}><input aria-label={label} type="number" min={min} max={max} value={Number(b[key]) / factor} onChange={e => { if (e.target.value) behavior({ [key]: Math.round(Math.min(max, Math.max(min, Number(e.target.value))) * factor) }); }} /></Property>;
  const sections = [['audience', 'Де і кому'], ['timing', 'Коли і як часто'], ['schedule', 'Розклад'], ['placement', 'Поведінка та розташування']];
  return <div className="pc-rules-layout"><nav aria-label="Налаштування правил">{sections.map(([id, title]) => <button type="button" key={id} aria-pressed={section === id} onClick={() => setSection(id)}>{title}</button>)}</nav><section className="pc-rule-content">
    {section === 'audience' && <><h2>Де і кому показувати</h2><p>Спочатку оберіть сторінки. Додаткові умови звужують цю аудиторію; виключення мають перевагу.</p><Choice label="Де показувати" value={t.mode} options={ [['all_pages', 'Усі сторінки'], ['all_products', 'Товарні сторінки'], ['out_of_stock', 'Сторінки відсутніх товарів'], ['products', 'Вибрані товари та модифікації'], ['target_page', 'Конкретна сторінка'], ...(t.mode === 'rules' ? [['rules', 'Збережені правила попереднього редактора'] as const] : [])] } onChange={mode => targeting({ mode })} />
      {t.mode === 'target_page' && <Property label="URL сторінки"><input aria-label="URL сторінки" value={t.targetPageUrl} onChange={e => targeting({ targetPageUrl: e.target.value })} /><small>Зіставляється адреса сторінки без параметрів і якоря. Для UTM використайте додаткову умову URL.</small></Property>}
      {t.mode === 'products' && <Property label="Артикули або точні назви товарів"><textarea aria-label="Артикули або точні назви товарів" value={input.productEntries.join('\n')} onChange={e => onChange({ ...input, productEntries: e.target.value.split('\n') })} /><small>Кожен із нового рядка. Модифікація — за її артикулом. Перевірка повідомить про нерозпізнані значення.</small></Property>}
      {t.mode === 'rules' && <div className="pc-callout"><p>Збережені фільтри: {JSON.stringify({ бренди: t.brands, категорії: t.categoryIds, наліпки: t.stickers, стан: t.conditions, URL: t.urlContains })}</p><button type="button" onClick={() => targeting({ mode: 'all_products', rules: { kind: 'group', match: t.match, children: (['brands', 'categoryIds', 'stickers', 'conditions', 'urlContains'] as const).filter(key => t[key].length).map(key => ({ kind: 'condition', field: ({ brands: 'brand', categoryIds: 'category', stickers: 'sticker', conditions: 'condition', urlContains: 'url' } as const)[key], operator: key === 'urlContains' ? 'contains' : 'is', values: t[key], descendants: false })) } })}>Перенести фільтри в нові групи</button></div>}
      <h3>Показати, коли</h3><RuleEditor value={t.rules || emptyGroup()} options={options} onChange={rules => targeting({ rules })} />
      <h3>Ніколи не показувати, коли</h3><p>Порожня група виключень нічого не виключає. Невідомі дані не підтверджують дозвіл на показ.</p><RuleEditor value={t.exclusions || { ...emptyGroup(), match: 'any' }} options={options} onChange={exclusions => targeting({ exclusions })} />
      <Choice label="Пристрої" value={b.device} options={ [['all', 'Усі'], ['desktop', 'Лише Desktop'], ['mobile', 'Лише Mobile']] } onChange={device => behavior({ device })} />
      <Property label="Пріоритет"><input aria-label="Пріоритет" type="number" min={0} max={1000} value={input.priority} onChange={e => onChange({ ...input, priority: Math.max(0, Math.min(1000, Number(e.target.value))) })} /></Property></>}
    {section === 'timing' && <><h2>Момент та частота показу</h2><Choice label="Коли показувати" value={b.trigger} options={ [['delay', 'Після затримки'], ['scroll', 'Після прокручування'], ['inactivity', 'Після бездіяльності'], ['exit_intent', 'Намір залишити сторінку']] } onChange={trigger => behavior({ trigger })} />{number('delayMs', 'Не раніше ніж, секунд', 0, 60, 1000)}{b.trigger === 'scroll' && number('scrollPercent', 'Прокручено, %', 5, 100)}{b.trigger === 'inactivity' && number('inactivitySeconds', 'Бездіяльність, секунд', 1, 300)}{b.trigger === 'exit_intent' && <p className="pc-callout">Desktop: курсор виходить через верхній край. Mobile: швидке повернення вгору після прокручування або повернення до вкладки після її приховування.</p>}<Choice label="Частота показу" value={b.frequency} options={ [['always', 'Кожен перегляд'], ['session', 'Раз за сесію'], ['product', 'Раз на товар'], ['hours', 'Раз на кілька годин'], ['days', 'Раз на кілька днів']] } onChange={frequency => behavior({ frequency })} />{b.frequency === 'hours' && number('cooldownHours', 'Інтервал, годин', 1, 8760)}{b.frequency === 'days' && number('cooldownDays', 'Інтервал, днів', 1, 365)}<label><input type="checkbox" checked={b.maxShowsPerSession > 0} onChange={e => behavior({ maxShowsPerSession: e.target.checked ? 1 : 0 })} /> Обмежити покази за сесію</label>{b.maxShowsPerSession > 0 && number('maxShowsPerSession', 'Максимум за сесію', 1, 20)}<p>Ліміт враховує факт показу. Закриття, підтвердження та успішна форма не скидають його. Нова публікація створює нову версію лічильників.</p></>}
    {section === 'schedule' && <><h2>Розклад кампанії</h2><Choice label="Часовий пояс кампанії" value={b.scheduleTimezone} options={ [['Europe/Kyiv', 'Київ'], ['Europe/Warsaw', 'Варшава'], ['Europe/Berlin', 'Берлін'], ['UTC', 'UTC']] } onChange={scheduleTimezone => behavior({ scheduleTimezone })} />{(['startsAt', 'endsAt'] as const).map(key => <Property key={key} label={key === 'startsAt' ? 'Початок показу' : 'Кінець показу'}><input type="datetime-local" aria-label={key === 'startsAt' ? 'Початок показу' : 'Кінець показу'} value={zonedDate(input[key], b.scheduleTimezone)} onChange={e => { const value = e.target.value; if (!value) { onChange({ ...input, [key]: null }); setDateError(''); return; } const instant = toInstant(value, b.scheduleTimezone); if (zonedDate(instant, b.scheduleTimezone) !== value) { setDateError('Цей час не існує через перехід на літній час. Оберіть інший.'); return; } setDateError(''); onChange({ ...input, [key]: instant }); }} /></Property>)}{dateError && <p role="alert">{dateError}</p>}<p>Дати, дні тижня та години нижче — у поясі {b.scheduleTimezone}. Порожня дата означає відсутність цієї межі.</p><div className="pb-weekdays">{['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'].map((day, i) => <label key={day}><input type="checkbox" checked={b.activeWeekdays.includes(i + 1)} disabled={b.activeWeekdays.length === 1 && b.activeWeekdays[0] === i + 1} onChange={e => behavior({ activeWeekdays: e.target.checked ? [...b.activeWeekdays, i + 1].sort() : b.activeWeekdays.filter(v => v !== i + 1) })} />{day}</label>)}</div><label><input type="checkbox" checked={Boolean(b.dailyStartTime)} onChange={e => behavior({ dailyStartTime: e.target.checked ? '09:00' : '', dailyEndTime: e.target.checked ? '21:00' : '' })} /> Обмежити години показу</label>{b.dailyStartTime && <div className="pc-inline">{(['dailyStartTime', 'dailyEndTime'] as const).map(key => <Property key={key} label={key === 'dailyStartTime' ? 'Від' : 'До'}><input type="time" aria-label={key === 'dailyStartTime' ? 'Від' : 'До'} value={b[key]} onChange={e => behavior({ [key]: e.target.value })} /></Property>)}</div>}<small>Інтервал може переходити через північ; день тижня перевіряється за поточним місцевим часом.</small></>}
    {section === 'placement' && <><h2>Поведінка та розташування</h2><Choice label="Формат показу" value={input.styles.layout} options={ [['modal', 'По центру із затемненням'], ['bottom-sheet', 'Знизу із затемненням'], ['corner', 'Плаваючий банер']] } onChange={layout => onChange({ ...input, styles: { ...input.styles, layout } })} />{input.styles.layout === 'corner' && <><Choice label="Положення Desktop" value={input.styles.desktopPosition} options={ [['top_left', 'Зверху ліворуч'], ['top_right', 'Зверху праворуч'], ['bottom_left', 'Знизу ліворуч'], ['bottom_right', 'Знизу праворуч']] } onChange={desktopPosition => onChange({ ...input, styles: { ...input.styles, desktopPosition } })} /><Choice label="Положення Mobile" value={input.styles.mobilePosition} options={ [['top', 'Зверху'], ['bottom', 'Знизу']] } onChange={mobilePosition => onChange({ ...input, styles: { ...input.styles, mobilePosition } })} /></>}<label><input type="checkbox" checked={b.dismissible} onChange={e => behavior({ dismissible: e.target.checked })} /> Кнопка закриття, Escape та клік поза банером</label><label><input type="checkbox" checked={b.requireAcknowledgement} onChange={e => behavior({ requireAcknowledgement: e.target.checked })} /> Вимагати позначку підтвердження перед дією</label><p>Додайте блок «Підтвердження» та кнопку з дією «Закрити банер». Поки покупець не поставить позначку, кнопки переходу, кошика та підтвердження неактивні. Звичайний хрестик залишається дією закриття.</p><label><input type="checkbox" checked={b.autoCloseSeconds > 0} onChange={e => behavior({ autoCloseSeconds: e.target.checked ? 10 : 0 })} /> Автоматично закривати</label>{b.autoCloseSeconds > 0 && number('autoCloseSeconds', 'Автозакриття, секунд', 1, 300)}</>}
  </section><aside className="pc-summary"><small>ПІДСУМОК ПОКАЗУ</small><h3>{input.name || 'Кампанія'}</h3><p>{{ all_pages: 'Усі сторінки', all_products: 'Товарні сторінки', out_of_stock: 'Лише сторінки відсутніх товарів', products: 'Вибрані товари', target_page: 'Конкретна сторінка', rules: 'Збережені правила каталогу' }[t.mode]}</p><p>{describeRules(t.rules, options)}</p>{t.exclusions?.children.length ? <p><strong>Виключення:</strong> {describeRules(t.exclusions, options)}</p> : null}<p>Пристрій: {b.device}. Не раніше {b.delayMs / 1000} с.</p><p>Пріоритет: {input.priority}. Одночасно показується одна кампанія з тих, що готові до показу.</p><p>Перевірте конкретну сторінку у вкладці «Перевірка».</p></aside></div>;
}
