import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { Choice } from './BlockInspector';
import type { PopupCampaignOptions } from '../../types/popup-banner';
import type { RuleCondition, RuleField, RuleGroup } from '../../../../src/modules/popup-banners/campaign-rules.js';

export const fieldLabels: Record<RuleField, string> = { page: 'Тип сторінки', stock: 'Наявність товару', product: 'Товар', sku: 'Артикул / модифікація', category: 'Категорія', brand: 'Бренд', sticker: 'Наліпка', condition: 'Стан товару', url: 'Повний URL', path: 'Шлях сторінки' };
export const emptyGroup = (): RuleGroup => ({ kind: 'group', match: 'all', children: [] });
export function ValuePicker({ label, values, options, onChange }: { label: string; values: string[]; options: { id: string; title: string }[]; onChange: (values: string[]) => void }) {
  const [search, setSearch] = useState('');
  return <div className="pc-value-picker"><div className="pc-tokens">{values.map(value => <button key={value} type="button" onClick={() => onChange(values.filter(v => v !== value))} aria-label={'Прибрати ' + (options.find(o => o.id === value)?.title || value)}>{options.find(o => o.id === value)?.title || value} ×</button>)}</div><input aria-label={label} placeholder="Знайти та додати…" value={search} onChange={e => setSearch(e.target.value)} /><div className="pc-options">{options.filter(o => !values.includes(o.id) && (o.title + ' ' + o.id).toLocaleLowerCase().includes(search.toLocaleLowerCase())).slice(0, 40).map(o => <button key={o.id} type="button" onClick={() => { onChange([...values, o.id]); setSearch(''); }}>＋ {o.title}</button>)}</div></div>;
}
function ConditionEditor({ rule, onChange, options }: { rule: RuleCondition; onChange: (rule: RuleCondition) => void; options?: PopupCampaignOptions }) {
  const [search, setSearch] = useState('');
  const [bulk, setBulk] = useState('');
  const catalog = useQuery({ queryKey: ['popup-rule-catalog', search], queryFn: ({ signal }) => api.popupBanners.catalog({ search, pageSize: 20 }, signal), enabled: rule.field === 'product' || rule.field === 'sku' });
  const choices = rule.field === 'page' ? [{ id: 'product', title: 'Товарна сторінка' }, { id: 'other', title: 'Інша сторінка' }] : rule.field === 'stock' ? [{ id: 'available', title: 'У наявності' }, { id: 'out_of_stock', title: 'Немає в наявності' }, { id: 'unknown', title: 'Не вдалося визначити' }] : rule.field === 'category' ? (options?.categories || []).map(c => ({ id: c.id, title: c.path || c.title })) : rule.field === 'brand' ? (options?.brands || []).map(v => ({ id: v, title: v })) : rule.field === 'condition' ? (options?.conditions || []).map(v => ({ id: v, title: v })) : rule.field === 'sticker' ? options?.stickers || [] : [];
  return <div className="pc-condition"><div className="pc-condition-head"><Choice label="Поле правила" value={rule.field} options={Object.entries(fieldLabels) as [RuleField, string][]} onChange={field => onChange({ ...rule, field, values: [], operator: 'is', descendants: false })} /><Choice label="Оператор" value={rule.operator} options={ [['is', 'Дорівнює одному з'], ['is_not', 'Не дорівнює жодному'], ...(['url', 'path'].includes(rule.field) ? [['contains', 'Містить один із фрагментів'] as const] : [])] } onChange={operator => onChange({ ...rule, operator })} /></div>
    {['product', 'sku'].includes(rule.field) ? <><div className="pc-tokens">{rule.values.map(v => <button type="button" key={v} onClick={() => onChange({ ...rule, values: rule.values.filter(item => item !== v) })}>{v} ×</button>)}</div><input aria-label="Пошук товарів для правила" placeholder="Назва або артикул товару…" value={search} onChange={e => setSearch(e.target.value)} /><div className="pc-options">{catalog.data?.items.flatMap(p => rule.field === 'product' ? [{ id: p.externalId, title: p.titles.uk || p.titles.ua || Object.values(p.titles)[0] || p.sku, sku: p.sku }] : [{ id: p.sku, title: p.titles.uk || p.titles.ua || Object.values(p.titles)[0] || p.sku, sku: p.sku }, ...p.modifications.map(m => ({ id: m.sku, title: m.titles.uk || m.titles.ua || Object.values(m.titles)[0] || m.sku, sku: m.sku }))]).filter(p => p.id && !rule.values.includes(p.id)).map(p => <button type="button" key={p.id} onClick={() => onChange({ ...rule, values: [...rule.values, p.id] })}>{p.title} · {p.sku}</button>)}</div>{catalog.error && <p role="alert">{catalog.error.message}</p>}{rule.field === 'sku' && <><textarea aria-label="Масове додавання артикулів" placeholder="Артикули через кому або з нового рядка" value={bulk} onChange={e => setBulk(e.target.value)} /><button type="button" onClick={() => { onChange({ ...rule, values: [...new Set([...rule.values, ...bulk.split(/[\n,;]/).map(v => v.trim()).filter(Boolean)])].slice(0, 100) }); setBulk(''); }}>Додати артикули</button><small>Зіставлення артикулів перевіряється у вкладці «Перевірка».</small></>}</> : ['url', 'path'].includes(rule.field) ? <textarea aria-label="Значення правила" value={rule.values.join('\n')} placeholder={rule.field === 'path' ? '/smartfony/' : 'https://магазин/сторінка'} onChange={e => onChange({ ...rule, values: e.target.value.split('\n') })} /> : <ValuePicker label={'Пошук: ' + fieldLabels[rule.field]} values={rule.values} options={choices} onChange={values => onChange({ ...rule, values })} />}
    {rule.field === 'category' && <label><input type="checkbox" checked={rule.descendants} onChange={e => onChange({ ...rule, descendants: e.target.checked })} /> Разом із дочірніми категоріями</label>}
    {!rule.values.length && <small className="pc-incomplete">Оберіть значення, щоб правило було готове.</small>}
  </div>;
}
export function RuleEditor({ value, onChange, options, depth = 0 }: { value: RuleGroup; onChange: (value: RuleGroup) => void; options?: PopupCampaignOptions; depth?: number }) {
  return <div className="pc-rule-group"><Choice label="Поєднання умов" value={value.match} options={ [['all', 'Усі умови одночасно — І'], ['any', 'Будь-яка умова — АБО']] } onChange={match => onChange({ ...value, match })} />{value.children.map((rule, i) => <div className="pc-rule" key={i}><div className="pc-rule-index"><span>{i + 1}</span><button type="button" aria-label={'Видалити правило ' + (i + 1)} onClick={() => onChange({ ...value, children: value.children.filter((_, n) => n !== i) })}>×</button></div>{rule.kind === 'group' ? <RuleEditor value={rule} depth={depth + 1} options={options} onChange={next => onChange({ ...value, children: value.children.map((item, n) => n === i ? next : item) })} /> : <ConditionEditor rule={rule} options={options} onChange={next => onChange({ ...value, children: value.children.map((item, n) => n === i ? next : item) })} />}</div>)}<div className="pc-inline"><button type="button" disabled={value.children.length >= 30} onClick={() => onChange({ ...value, children: [...value.children, { kind: 'condition', field: 'stock', operator: 'is', values: ['out_of_stock'], descendants: false }] })}>＋ Умова</button>{depth < 4 && <button type="button" onClick={() => onChange({ ...value, children: [...value.children, emptyGroup()] })}>＋ Група умов</button>}</div></div>;
}
export function describeRules(group?: RuleGroup, options?: PopupCampaignOptions): string {
  if (!group?.children.length) return 'без додаткових обмежень';
  return group.children.map(rule => rule.kind === 'group' ? '(' + describeRules(rule, options) + ')' : fieldLabels[rule.field] + ' ' + ({ is: '=', is_not: '≠', contains: 'містить' }[rule.operator]) + ' ' + rule.values.map(v => rule.field === 'category' ? options?.categories.find(c => c.id === v)?.path || v : ({ available: 'у наявності', out_of_stock: 'відсутній', unknown: 'невідомо', product: 'товарна сторінка' }[v] || v)).join(', ') + (rule.descendants ? ' з підкатегоріями' : '')).join(group.match === 'all' ? ' І ' : ' АБО ');
}
